// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMHzqF4Z-A94zE0W5qcX5qomz16lsQjHs',
    appId: '1:1036348094360:web:29bd45ab295a1780199ded',
    messagingSenderId: '1036348094360',
    projectId: 'edubridge-firebase',
    authDomain: 'edubridge-firebase.firebaseapp.com',
    storageBucket: 'edubridge-firebase.firebasestorage.app',
    measurementId: 'G-6RLCVFF40X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD9Rf4zsSHxDpgFrXyV_bOGOlVWabxG7A',
    appId: '1:1036348094360:android:41bc1ff29756d621199ded',
    messagingSenderId: '1036348094360',
    projectId: 'edubridge-firebase',
    storageBucket: 'edubridge-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxV7aYHY8-gbWGO0oTlgu6BzcMtUDIS54',
    appId: '1:1036348094360:ios:aaa27ce761c371bc199ded',
    messagingSenderId: '1036348094360',
    projectId: 'edubridge-firebase',
    storageBucket: 'edubridge-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterEdubridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxV7aYHY8-gbWGO0oTlgu6BzcMtUDIS54',
    appId: '1:1036348094360:ios:aaa27ce761c371bc199ded',
    messagingSenderId: '1036348094360',
    projectId: 'edubridge-firebase',
    storageBucket: 'edubridge-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterEdubridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMHzqF4Z-A94zE0W5qcX5qomz16lsQjHs',
    appId: '1:1036348094360:web:3a22bcadc1937607199ded',
    messagingSenderId: '1036348094360',
    projectId: 'edubridge-firebase',
    authDomain: 'edubridge-firebase.firebaseapp.com',
    storageBucket: 'edubridge-firebase.firebasestorage.app',
    measurementId: 'G-YXJS5PESBJ',
  );
}
